--- 
__default__: ~
cluster: "mkdir -p logs/`date +\"%d-%m-%y\"`/{rule} && sbatch --cpus-per-task={threads} --mem={resources.mem_mb} --job-name=snkmk-{rule}-{wildcards} --output=logs/`date +\"%d-%m-%y\"`/{rule}/{jobid}-{wildcards}.out --error=logs/`date +\"%d-%m-%y\"`/{rule}/{jobid}-{wildcards}.err --mail-user=darina.obukhova@mumc.nl --mail-type=END,FAIL"
local-cores: 2
default-resources: 
  - partition=research
  - mem_mb=2000
jobs: 100
keep-going: true
latency-wait: 100
printshellcmds: true
rerun-incomplete: true
restart-times: 1
max-jobs-per-second: 20
show-failed-logs: true
snakefile: SnakeFile
use-singularity: true
